apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: ems-frontend
  description: Employee Management System Frontend

  annotations:
    github.com/project-slug: rajudruva2/ems-frontend
    backstage.io/techdocs-ref: dir:.

spec:
  type: website
  lifecycle: production
  owner: user:default/rajudruva2
  system: ems-platform
